//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTS.Data.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personnel
    {
        public int PERSON_ID { get; set; }
        public string NAME { get; set; }
        public string DEFAULT_FACILITY_ID { get; set; }
        public string FACILITY_ID { get; set; }
        public string LOGIN { get; set; }
        public int PIN { get; set; }
        public string API_KEY { get; set; }
        public bool IS_ADMIN { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    }
}
