//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTS.Data.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Printer
    {
        public string ID { get; set; }
        public string STATUS { get; set; }
        public int ERRORS { get; set; }
        public int COMPLETE { get; set; }
        public string FACILITY_ID { get; set; }
        public string NETWORK { get; set; }
        public Nullable<int> INTERVAL { get; set; }
        public string MODEL { get; set; }
        public byte[] LAST_SEEN { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    }
}
