//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTS.Data.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProgisticsEntities : DbContext
    {
        public ProgisticsEntities()
            : base("name=ProgisticsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<Facility> Facilities { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<Personnel> Personnels { get; set; }
        public virtual DbSet<Printer> Printers { get; set; }
        public virtual DbSet<PrintJob> PrintJobs { get; set; }
        public virtual DbSet<Truckload> Truckloads { get; set; }
        public virtual DbSet<Waybill> Waybills { get; set; }
    }
}
