//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTS.Data.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Truckload
    {
        public int TRUCKLOAD_ID { get; set; }
        public int WAYBILL_ID { get; set; }
        public int ITEM_ID { get; set; }
        public bool IS_BATCH { get; set; }
        public string STATUS { get; set; }
        public Nullable<int> WAYBILL_COUNT { get; set; }
        public Nullable<int> ITEM_COUNT { get; set; }
        public string OPEN_LIST { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    }
}
