//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTS.Data.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Waybill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Waybill()
        {
            this.Items = new HashSet<Item>();
        }
    
        public int WAYBILL_ID { get; set; }
        public string SRC_ADDRESS1 { get; set; }
        public string SRC_ADDRESS2 { get; set; }
        public string SRC_ADDRESS3 { get; set; }
        public string SRC_CITY { get; set; }
        public string SRC_STATE { get; set; }
        public string SRC_ZIP { get; set; }
        public string DEST_ADDRESS1 { get; set; }
        public string DEST_ADDRESS2 { get; set; }
        public string DEST_ADDRESS3 { get; set; }
        public string DEST_CITY { get; set; }
        public string DEST_STATE { get; set; }
        public string DEST_ZIP { get; set; }
        public string SRC_NAME { get; set; }
        public string DEST_NAME { get; set; }
        public string SHIPMENT_ID { get; set; }
        public string SHIPMENT_REF { get; set; }
        public string FINAL_FACILITY_ID { get; set; }
        public string NOTES { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item> Items { get; set; }
    }
}
